Job:
    run_mode: "Training"  
    #{Training, Predict, Repeat, CV, Hyperparameter, Ensemble, Analysis}
    Training:
        job_name: "my_train_job"
        reprocess: "False"    
        model: CGCNN_demo   
        load_model: "False"
        save_model: "True"
        model_path: "my_model.pth"
        write_output: "True"
        parallel: "True"
        #seed=0 means random initalization
        seed: 875360
    Predict:
        job_name: "my_predict_job"
        reprocess: "False"    
        model_path: "my_model.pth"
        write_output: "True"
        seed: 204531   
    Repeat:
        job_name: "my_repeat_job"
        reprocess: "False"    
        model: CGCNN_demo   
        model_path: "my_model.pth"
        write_output: "False"
        parallel: "True"
        seed: 846589      
        ###specific options
        #number of repeat trials
        repeat_trials: 5
    CV:
        job_name: "my_CV_job"
        reprocess: "False"    
        model: CGCNN_demo   
        write_output: "True"
        parallel: "True"
        seed: 204531    
        ###specific options
        #number of folds for n-fold CV
        cv_folds: 5    
    Hyperparameter:
        job_name: "my_hyperparameter_job"
        reprocess: "False"    
        model: GATEDGIN_demo   
        seed: 0  
        ###specific options   
        hyper_trials: 10
        #number of concurrent trials (can be greater than number of GPUs)
        hyper_concurrency: 8
        #frequency of checkpointing and update (default: 1)
        hyper_iter: 1
        #resume a previous hyperparameter optimization run
        hyper_resume: "True"
        #Verbosity of ray tune output; available: (1, 2, 3)
        hyper_verbosity: 1
        #Delete processed datasets
        hyper_delete_processed: "True"
    Ensemble:
        job_name: "my_ensemble_job"
        reprocess: "False"     
        save_model: "True"
        model_path: "my_model.pth"
        write_output: "Partial"
        parallel: "True"
        seed: 0   
        ###specific options  
        #List of models to use: (Example: "CGCNN_demo,MPNN_demo,SchNet_demo,MEGNet_demo" or "CGCNN_demo,CGCNN_demo,CGCNN_demo,CGCNN_demo")
        # ensemble_list: "CGCNN_demo,CGCNN_demo,CGCNN_demo,CGCNN_demo,CGCNN_demo"
        ensemble_list: "GGCN_demo,SOAP_demo"
    Analysis:
        job_name: "my_job" 
        reprocess: "False"   
        model: CGCNN_demo   
        model_path: "my_model.pth"
        write_output: "True"
        seed: 0     
    
Processing:
    #Whether to use "inmemory" or "large" format for pytorch-geometric dataset. Reccomend inmemory unless the dataset is too large
    dataset_type: "inmemory"  
    #Path to data files
    data_path: "/data" 
    #Path to target file within data_path
    target_path: "targets.csv"
    #Whether to process targets
    targets: "True"
    # Size of splits of data (0 for no split)
    split_size: 10000
    #Method of obtaining atom idctionary: available:(provided, default, blank, generated)
    dictionary_source: "provided"   
    #Path to atom dictionary file within data_path
    dictionary_path: "atom_dict_216.json"     
    #Format of data files (limit to those supported by ASE)
    data_format: "cif"
    #Print out processing info 
    verbose: "True"
    #graph specific settings 
    graph_max_radius : 8.0
    graph_max_neighbors : 12
    voronoi: "False"
    edge_features: "True"
    graph_edge_length : 50 
    #SM specific settings
    SM_descriptor: "False"
    #SOAP specific settings
    SOAP_descriptor: "False"
    SOAP_rcut : 8.0
    SOAP_nmax : 6
    SOAP_lmax : 4
    SOAP_sigma : 0.3

Training:     
    #Index of target column in targets.csv
    target_index: 0
    #Loss functions (from pytorch) examples: l1_loss, mse_loss, binary_cross_entropy
    loss: "l1_loss"       
    #Ratios for train/val/test split out of a total of 1  
    train_ratio: 0.7
    val_ratio: 0.1
    test_ratio: 0.2
    #Training print out frequency (print per n number of epochs)
    verbosity: 10
    
Models:
    Matformer_demo:
        model: Matformer
        conv_layers: 2
        node_features: 64
        edge_features: 64
        fc_layers: 4
        fc_features: 512
        node_layer_head: 2
        link: "identity"
        zero_inflated: "False"
        pool: "global_mean_pool"
        batch_norm: "True"
        batch_track_stats: "True"
        act: "silu"
        dropout_rate: 0.0
        epochs: 50
        lr: 0.0005
        batch_size: 100
        optimizer: "AdamW"
        optimizer_args: {"weight_decay":0.0001}
        scheduler: "ReduceLROnPlateau"
        scheduler_args: {"mode":"min", "factor":0.5, "patience":10, "min_lr":0.00001, "threshold":0.0002}
    Matformer_AUG_demo:
        model: Matformer_AUG
        conv_layers: 2
        node_features: 64
        edge_features: 64
        fc_layers: 4
        fc_features: 64
        node_layer_head: 3
        link: "identity"
        zero_inflated: "False"
        pool: "global_mean_pool"
        batch_norm: "True"
        batch_track_stats: "True"
        act: "silu"
        dropout_rate: 0.0
        epochs: 50
        lr: 0.0005
        batch_size: 100
        optimizer: "AdamW"
        optimizer_args: {"weight_decay":0.0001}
        scheduler: "ReduceLROnPlateau"
        scheduler_args: {"mode":"min", "factor":0.5, "patience":10, "min_lr":0.00001, "threshold":0.0002}
    GGCN_demo:
        model: GGCN
        dim1: 128
        dim2: 64
        pre_fc_count: 1
        gc_count: 2
        post_fc_count: 6
        pool: "global_mean_pool"
        pool_order: "early"
        batch_norm: "True"
        batch_track_stats: "True"
        act: "silu"
        dropout_rate: 0.0
        epochs: 50
        lr: 0.0005
        batch_size: 300
        optimizer: "AdamW"
        optimizer_args: {}
        scheduler: "ReduceLROnPlateau"
        scheduler_args: {"mode":"min", "factor":0.8, "patience":10, "min_lr":0.00001, "threshold":0.0002}
    GGCN_EDGE_demo:
        model: GGCN_EDGE
        dim1: 128
        dim2: 128
        pre_fc_count: 1
        gc_count: 2
        post_fc_count: 4
        pool: "global_mean_pool"
        pool_order: "early"
        batch_norm: "True"
        batch_track_stats: "True"
        act: "silu"
        dropout_rate: 0.0
        epochs: 50
        lr: 0.0005
        batch_size: 300
        optimizer: "AdamW"
        optimizer_args: {}
        scheduler: "ReduceLROnPlateau"
        scheduler_args: {"mode":"min", "factor":0.8, "patience":10, "min_lr":0.00001, "threshold":0.0002}
    GGCN_AUG_demo:
        model: GGCN_AUG
        dim1: 128
        dim2: 512
        pre_fc_count: 1
        gc_count: 2
        post_fc_count: 6
        pool: "global_mean_pool"
        pool_order: "early"
        batch_norm: "True"
        batch_track_stats: "True"
        act: "silu"
        dropout_rate: 0.0
        epochs: 50
        lr: 0.005
        batch_size: 300
        optimizer: "AdamW"
        optimizer_args: {}
        scheduler: "ReduceLROnPlateau"
        scheduler_args: {"mode":"min", "factor":0.8, "patience":10, "min_lr":0.00001, "threshold":0.0002}
    GATGNN_demo:
        model: GATGNN
        dim: 100
        pre_fc_count: 1
        gc_count: 3
        post_fc_count: 6
        pool: "global_mean_pool"
        pool_order: "early"
        batch_norm: "True"
        batch_track_stats: "True"
        act: "silu"
        dropout_rate: 0.0
        epochs: 100
        lr: 0.005
        batch_size: 200
        optimizer: "AdamW"
        optimizer_args: {}
        scheduler: "ReduceLROnPlateau"
        scheduler_args: {"mode": "min", "factor": 0.8, "patience": 10, "min_lr": 0.00001, "threshold": 0.0002}
    CGCNN_demo:
        model: CGCNN
        dim1: 64
        dim2: 512
        pre_fc_count: 1
        gc_count: 2
        post_fc_count: 4
        pool: "global_mean_pool"
        pool_order: "early"
        batch_norm: "True"
        batch_track_stats: "True"
        act: "relu"
        dropout_rate: 0.0
        epochs: 50
        lr: 0.0005
        batch_size: 200
        optimizer: "AdamW"
        optimizer_args: {}
        scheduler: "ReduceLROnPlateau"
        scheduler_args: {"mode":"min", "factor":0.8, "patience":10, "min_lr":0.00001, "threshold":0.0002}     
    CGCNN_AUG_demo:
        model: CGCNN_AUG
        dim1: 128
        dim2: 512
        pre_fc_count: 1
        gc_count: 2
        post_fc_count: 4
        pool: "global_mean_pool"
        pool_order: "early"
        batch_norm: "True"
        batch_track_stats: "True"
        act: "relu"
        dropout_rate: 0.0
        epochs: 50
        lr: 0.0005
        batch_size: 200
        optimizer: "AdamW"
        optimizer_args: {}
        scheduler: "ReduceLROnPlateau"
        scheduler_args: {"mode":"min", "factor":0.8, "patience":10, "min_lr":0.00001, "threshold":0.0002}                      
    MPNN_demo:
        model: MPNN
        dim1: 64
        dim2: 64
        dim3: 64
        pre_fc_count: 1
        gc_count: 3
        post_fc_count: 6
        pool: "global_mean_pool"
        pool_order: "early"
        batch_norm: "True"
        batch_track_stats: "True"
        act: "relu"
        dropout_rate: 0.0
        epochs: 50
        lr: 0.0005
        batch_size: 15
        optimizer: "AdamW"
        optimizer_args: {}
        scheduler: "ReduceLROnPlateau"
        scheduler_args: {"mode":"min", "factor":0.8, "patience":10, "min_lr":0.00001, "threshold":0.0002}         
    MPNN_AUG_demo:
        model: MPNN_AUG
        dim1: 64
        dim2: 64
        dim3: 64
        pre_fc_count: 1
        gc_count: 2
        post_fc_count: 4
        pool: "global_mean_pool"
        pool_order: "early"
        batch_norm: "True"
        batch_track_stats: "True"
        act: "relu"
        dropout_rate: 0.0
        epochs: 50
        lr: 0.001
        batch_size: 15
        optimizer: "AdamW"
        optimizer_args: {}
        scheduler: "ReduceLROnPlateau"
        scheduler_args: {"mode":"min", "factor":0.8, "patience":10, "min_lr":0.00001, "threshold":0.0002}     
    SchNet_demo:
        model: SchNet
        dim1: 64
        dim2: 512
        dim3: 128
        cutoff: 8
        pre_fc_count: 1
        gc_count: 2
        post_fc_count: 4
        pool: "global_mean_pool"
        pool_order: "early"
        batch_norm: "True"
        batch_track_stats: "True"
        act: "relu"
        dropout_rate: 0.0
        epochs: 50
        lr: 0.0005
        batch_size: 100
        optimizer: "AdamW"
        optimizer_args: {}
        scheduler: "ReduceLROnPlateau"
        scheduler_args: {"mode":"min", "factor":0.8, "patience":10, "min_lr":0.00001, "threshold":0.0002}        
    SchNet_AUG_demo:
        model: SchNet_AUG
        dim1: 128
        dim2: 256
        dim3: 64
        cutoff: 8
        pre_fc_count: 1
        gc_count: 2
        post_fc_count: 4
        pool: "global_mean_pool"
        pool_order: "early"
        batch_norm: "True"
        batch_track_stats: "True"
        act: "relu"
        dropout_rate: 0.0
        epochs: 50
        lr: 0.001
        batch_size: 100
        optimizer: "AdamW"
        optimizer_args: {}
        scheduler: "ReduceLROnPlateau"
        scheduler_args: {"mode":"min", "factor":0.8, "patience":10, "min_lr":0.00001, "threshold":0.0002}    
    MEGNet_demo:
        model: MEGNet
        dim1: 64
        dim2: 64
        dim3: 64
        pre_fc_count: 1
        gc_count: 2
        gc_fc_count: 1
        post_fc_count: 4
        pool: "global_mean_pool"
        pool_order: "early"
        batch_norm: "True"
        batch_track_stats: "True"
        act: "relu"
        dropout_rate: 0.0
        epochs: 50
        lr: 0.001
        batch_size: 200
        optimizer: "AdamW"
        optimizer_args: {}
        scheduler: "ReduceLROnPlateau"
        scheduler_args: {"mode":"min", "factor":0.8, "patience":10, "min_lr":0.00001, "threshold":0.0002}              
    MEGNet_AUG_demo:
        model: MEGNet_AUG
        dim1: 64
        dim2: 64
        dim3: 128
        pre_fc_count: 1
        gc_count: 2
        gc_fc_count: 1
        post_fc_count: 4
        pool: "global_mean_pool"
        pool_order: "early"
        batch_norm: "True"
        batch_track_stats: "True"
        act: "relu"
        dropout_rate: 0.0
        epochs: 50
        lr: 0.001
        batch_size: 200
        optimizer: "AdamW"
        optimizer_args: {}
        scheduler: "ReduceLROnPlateau"
        scheduler_args: {"mode":"min", "factor":0.8, "patience":10, "min_lr":0.00001, "threshold":0.0002}   
    GCN_demo:
        model: GCN
        dim1: 100 
        dim2: 150
        pre_fc_count: 1
        gc_count: 4
        post_fc_count: 3
        pool: "global_mean_pool"
        pool_order: "early"
        batch_norm: "True"
        batch_track_stats: "True"
        act: "relu"
        dropout_rate: 0.0
        epochs: 250
        lr: 0.002
        batch_size: 100
        optimizer: "AdamW"
        optimizer_args: {}
        scheduler: "ReduceLROnPlateau"
        scheduler_args: {"mode":"min", "factor":0.8, "patience":10, "min_lr":0.00001, "threshold":0.0002}     
    SM_demo:
        model: SM
        dim1: 100
        fc_count: 2
        epochs: 200
        lr: 0.002
        batch_size: 100
        optimizer: "AdamW"
        optimizer_args: {}
        scheduler: "ReduceLROnPlateau"
        scheduler_args: {"mode":"min", "factor":0.8, "patience":10, "min_lr":0.00001, "threshold":0.0002}               
    SOAP_demo:
        model: SOAP
        dim1: 100
        fc_count: 4
        epochs: 100
        lr: 0.002
        batch_size: 200
        optimizer: "AdamW"
        optimizer_args: {}
        scheduler: "ReduceLROnPlateau"
        scheduler_args: {"mode":"min", "factor":0.8, "patience":10, "min_lr":0.00001, "threshold":0.0002}

